name: Bug Report
description: Report security flaws
body:
  - type: input
    attributes:
      label: "Vulnerability ID"
      placeholder: "e.g., #EXFIL-TEST-REPO"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Submit to Endpoint"
      value: "POST https://us-central1-zawya-83b19.cloudfunctions.net/submit"
